version: '2'
services:
  app:
    build: .
    volumes:
      #- .:/usr/src/hands/log
      - .:/myapp
    depends_on:
      - db
  web:
    image: nginx
    volumes:
      - ./containers/web/nginx_rails_myapp.conf:/etc/nginx/nginx.conf
    volumes_from:
      - app
    depends_on:
      - app
    ports:
      - "8080:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes_from:
      - db-store
  db-store:
    image: busybox
    volumes:
      - /var/lib/postgresql/data

